### ISSUE TITLE
app-portage/portage-bashrc-mv: add USE flags for specific scripts?

### ISSUE THREAD

**Issue by InBetweenNames** [vaeth/mv-overlay#3]
First off I just want to say thank you for the awesome project.  `package.cflags` is exactly what I need currently.

I was wondering if you would be willing to accept a PR for `app-portage/portage-bashrc-mv` that adds USE flags for the individual scripts to install into `bashrc.d`?  For example, `USE="cflags title"` would install `10-title.sh` and `40-flag.sh` in there.  The reason for this is that I'm strongly considering migrating my own GentooLTO project over to `bashrc.d`, and it would be really nice if I could just add to my dependencies `app-portage/portage-bashrc-mv[cflags]` since the project doesn't really depend on the other functionality in there.  That way users could directly upgrade and gain the benefits of the new approach.  If this is something you'd be willing to have, I would gladly set up a PR for it to modify the ebuild.

**Comment by vaeth** [comment]
I think it is a bit exaggerated for a project consisting essentially only of 5 small files to have 5 individual USE-flag, each of which essentially controlling only the installation of one small file. This would be like controlling e.g. each individual {bash,zsh}-completion file by a separate USE-flag.

Especially, since the files reside in a CONFIG_PROTECTed directory, and so the user can easily remove them if he does nto want some of them (or he can deactivate them by setting corresponding environment variables in his make.conf).

Couldn't you just depend on app-portage/portage-bashrc-mv?
Or to cover the case that I change my mind on app-portage/portage-bashrc-mv[cflags(+)]?

In any case, I would consider it dangerous to write an ebuild which places files into /etc/portage/package.* since IMHO these should be user controlled. That's why there is no ebuild for https://github.com/vaeth/portage-env-mv/

**Comment by InBetweenNames** [comment]
I could just depend on `app-portage/portage-bashrc-mv`, yes.  However I wouldn't want users of `sys-config/ltoize` to pull in a bunch of extra stuff they may not need, since only `package.cflags` is really needed at this time.  Currently `app-portage/portage-bashrc-mv` installs all functionality and enables it by default, expecting the user to manually go in and tweak things.  Not that I'm against that necessarily--I thought this change just might make it a little easier.

What if instead these scripts were installed into a `bashrc.d.avail` and then symlinked into `bashrc.d` instead?  We can forego the USE flags this way.  

While it would be nice if ebuilds didn't place files into `/etc/portage/package.*` directly, I'm not sure how we would make `sys-config/ltoize` work without it.  Initially we wanted to create an LTO "profile" that would have the env overrides already in place which could be updated through layman.  Unfortunately, profiles don't support `package.env` functionality.  So this is the best we've got right now.

**Comment by vaeth** [comment]
After thinking it over: For all 5 scripts with the exception of remove_la, it makes sense to pull in special dependencies if they are installed (i.e. supposed to be used). This indeed justifies the introduction of USE-flags (and then remove_la will also be included for consistency). I will implement this in the mv overlay, no PR necessary.

**Comment by InBetweenNames** [comment]
Thank you!  This is exactly what I needed!
