### ISSUE TITLE
googleearth-bin: libicudata.so.54: ELF load command address/offset not page-aligned

### ISSUE THREAD

**Issue by GrantEdwards** [vaeth/mv-overlay#33]
I just installed googleearth-7.3.4-r1, and it fails to start:

~~~
$ googleearth 
/opt/googleearth/googleearth-bin: error while loading shared libraries: libicudata.so.54: ELF load command address/offset not page-aligned
~~~

I've googled that "not page-aligned" error, but didn't find anything that seemed relevant. There were plenty of hits, but they all seemed to be somewhat unrelated though they often involved Python and appimage/docker, and nobody ever had a rational explanation or solution.

Any ideas what might cause this problem?

**Comment by vaeth** [comment]
I do not know; this version of the ebuild just works here. Perhaps some feature of the base system (kernel/gcc/glibc) is needed. Shot in the dark, without knowing whether it is relevant: Do you perhaps have a 64-bit only system?

**Comment by GrantEdwards** [comment]
> I do not know; this version of the ebuild just works here. Perhaps some feature of the base system (kernel/gcc/glibc) is needed.

Thanks, one of my guesses was that it might have something to do with patchelf versions, but it doesn't look like that's changed much recently.

> Shot in the dark, without knowing whether it is relevant: Do you perhaps have a 64-bit only system?

Nope. I don't have a ton of 32-bit libraries installed, but common ones like libg are there, and I regularly use a few 32-bit apps. I asked 'file' about some of the object files that googleearth installed --- IIRC, all the ones I checked were 64-bit.

**Comment by vaeth** [comment]
Here: patchelf-0.17.0, glibc-2.36-7, but ~amd64 versions of gcc, binutils, glibc, gentoo-sources.

**Comment by vaeth** [comment]
Oh, when re-installing googleearth, I get now the same error.
So maybe you are right the patchelf or the way how it is used is the problem.

**Comment by vaeth** [comment]
Finally, I found time for some investigation.
It seems that libicudata.so.* has to be excluded from the patchelf modifications:
For googleearth-7.3.4, this is fine, because in this version the lib is statically linked, anyway.
For the older versions for googleearth, the lib is not linked statically, but the only dependencies listed are glibc (which are perhaps only artificially added, anyway), so “practically” it is statically linked anyway, and not modifying it should be fine.

The mv overlay is correspondingly updated. Therefore considering the issue as fixed.
